### ISSUE TITLE
Navigating problem when using Dropzone package

### ISSUE THREAD

**Issue by Isaac37** [deakjahn/flutter_dropzone#35]
am using flutter_dropzone, when i navigate to the next page the contents of the previous page(where dropzone is used) get stuck on the next page

**Comment by CrisNegoianu** [comment]
Hi.
I can confirm that I'm experiencing the same problem on the flutter beta channel.
I wasn't sure if this is a problem introduced by the latest flutter update or the package itself, so I was waiting for the next flutter version, which should be released in the next few days.

**Comment by deakjahn** [comment]
Because I never heard about anything similar, it might be Flutter, I don't know. Could you come up with a small sample to try?

**Comment by deakjahn** [comment]
First, I was thinking more about some source code to reproduce, not merely a screenshot. :-))

Could you also try with the other engine (HTML if you use CanvasKit or vice versa)? This reminds me of an older problem that was since fixed in Flutter, it was also related to one of the engines, CK I think.

**Comment by CrisNegoianu** [comment]
Hi.
I've just upgraded to the latest Flutter version released on the beta channel this morning and the issue seems to have gone away.
It would be good if other people could confirm this.

**Comment by AlexanderMityaev** [comment]
Hi.

Tested again without upgrade
 Flutter (Channel beta, 2.6.0-5.2.pre, on macOS 11.6 20G165 darwin-x64, locale en-GB).

With canvasKit: problem persists, no "ghost" on canvas but navigation/rendering broken;
With HTML: no such issue.

After flutter upgrade
Flutter (Channel beta, 2.7.0-3.0.pre, on macOS 11.6 20G165 darwin-x64, locale en-GB)
issue not reproduced with canvasKit, at least at preliminary quick debug run. Guess need further tests.

p.s. not related to original issue, but strange behaviour appears after upgrade to 2.7.0: all pages begun rendered as sliding from right %) with fast navigation between pages looks like UI "shaking".
